### ISSUE TITLE
outdated kernel

### ISSUE THREAD

**Issue by ekpyron** [yeacreate-opensources/kernel#1]
The current ntablet kernel is horribly outdated.
However, the git repository does not allow to easily judge which modifications were done to the upstream kernel.

Do you intend to update your fork to a non-ancient kernel version?
Is there any documentation about the modifications to the upstream kernel available?
Have you considered to maintain a well-documented patchset (which can be more easily adjusted across upstream updates) instead of a full fork instead?

**Comment by simonchen007** [comment]
We are upgrading the Kernel as 4.19 currently. but many works to do , so, we need more time.
